---
title: I got my internship!
author: Kaiwen Teoh
date: '2018-07-29'
slug: internship
categories: []
tags: []
---
  
  Yes, I finally got my internship for the coming new trimester. Even though going that company is not my original plan and it is located quite far away from my bed but well, half a loaf is better than none. I'm still going to work there and I appreciate it.
  
  One of the interesting parts that I want to share here is after my interview via Skype, I was given a R test to show my ability in analytic skill as well as familiarity in R programming(even though not so good but I have to). So, one dataset was attached and all I needed to do was prepare a report in order to share my outcomes and results.
  
  Overall, I would say that it's quite a pleasant experience and I enjoyed it since I have never involved myself in any R test like this before. It points out what I'm lack of in certain criteria and my weakness which still need to be improved in future. 
  
  Data visualisation is one of the crucial part in doing my report and overall I had used the base library of R in visualizing data instead of **ggplot2**. Of course, you might doubt why I made my life difficult by using the complicated syntax of built-in R functions in plotting my graphs. My answer will be the flexibility. Yes, flexibility. R built-in functions in data visualization provide greater flexibility compared to some awesome visualisation packages such as **ggplot2**. I learned the basic plotting functions before I come into ggplot2, that's why I used that despite I hate to set the location and axis of my legend in the pie and grouped bar chart on my own. 
  
  While the format of my report is prepared in Rmarkdown(.rmd). By using the **knitr** package, I'm able to knit my Rmarkdown document to HTML, pdf and word format. Rmarkdown is great and it not only allows us to embed R code chunk but also other programming languages like Julia and Python. What I'm like the most is you can even insert some HTML elements inside document if you didn't know markdown very well (Like what I'm doing right now).
  
  Last, you can refer my work [here]() on my project. The given dataset that I used for this analysis might not be a true dataset and you will find out why I'd say so if you notice carefully.

  
  
  
  
  
  
  
  
  
  